### ISSUE TITLE
Can not compile class

### ISSUE THREAD

**Issue by RonkTsang** [andrei-markeev/ts2c#61] opened 2020-01-02 10:17 UTC
I try some code in playground, and I get a Error when I try to write `class`.

``` js
// code:
function A() {
  this.a = 2
}

A.prototype.change = function () {
  this.a = 3
}
```
and I got the Error: 
```
Transpilation failed. TypeError: Cannot read property 'length' of undefined
```

**This project is cool** ~

**Comment by andrei-markeev** [comment] 2020-01-03 14:31
`prototype` is not yet supported. Currently finalizing closures, probably prototypes will be the next step after that.

**Comment by andrei-markeev** [comment] 2024-12-28 08:54
duplicate of #68

**Closed by andrei-markeev** 2024-12-28 08:54 UTC
